# Generated by Django 3.2.2 on 2021-05-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('img_url', models.ImageField(upload_to='img', verbose_name='商品图片地址')),
                ('price', models.IntegerField(verbose_name='单价')),
                ('intro', models.TextField(verbose_name='介绍')),
                ('unit', models.CharField(choices=[(1, '斤'), (2, '克'), (3, '俩')], default=2, max_length=30, verbose_name='重量')),
            ],
            options={
                'verbose_name_plural': '商品列表',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '锁定')], default=0, verbose_name='订单状态')),
                ('time', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('user_name', models.CharField(max_length=20, verbose_name='下单用户昵称')),
                ('phone', models.CharField(max_length=30, verbose_name='下单用户手机号')),
                ('address', models.CharField(max_length=200, verbose_name='下单用户地址')),
                ('total_price', models.IntegerField(verbose_name='商品价格')),
                ('pay_status', models.IntegerField(choices=[(1, '完成'), (2, '取消')], default=0, verbose_name='是否完成状态')),
            ],
            options={
                'verbose_name_plural': '订单表',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, unique=True, verbose_name='商品类别')),
            ],
            options={
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='用户名称')),
                ('pwd', models.CharField(max_length=200, verbose_name='用户密码')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '锁定')], default=1, verbose_name='状态')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name_plural': '用户列表',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=30, verbose_name='下单的商品名称')),
                ('price', models.IntegerField(verbose_name='下单商品的价格')),
                ('num', models.IntegerField(verbose_name='下单商品的个数')),
                ('img_url', models.CharField(max_length=100, verbose_name='商品图片')),
                ('total_price', models.IntegerField(verbose_name='总价格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.order', verbose_name='订单id')),
            ],
            options={
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.user', verbose_name='下单用户id'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unm', models.IntegerField(verbose_name='用户名称')),
                ('goods', models.ManyToManyField(to='ttsx_dev.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.user', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Adderss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='用户昵称')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='手机号')),
                ('address', models.CharField(max_length=200, verbose_name='收货地址')),
                ('is_default', models.IntegerField(verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.user')),
            ],
            options={
                'verbose_name_plural': '收货地址',
            },
        ),
    ]
