# Generated by Django 3.1.7 on 2021-04-30 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('time', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('pay_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('phone', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('num', models.IntegerField()),
                ('img_url', models.CharField(max_length=100)),
                ('total_price', models.FloatField(max_length=100)),
                ('order_id', models.IntegerField()),
                ('order_OrderDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.orderdetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.user'),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100)),
                ('img_url', models.ImageField(upload_to='img')),
                ('price', models.FloatField(max_length=100)),
                ('intro', models.CharField(max_length=100)),
                ('unit', models.CharField(default='克', max_length=100)),
                ('type_id', models.IntegerField()),
                ('Type', models.ManyToManyField(to='ttsx_dev.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unm', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('good_id', models.IntegerField()),
                ('user_Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.user')),
            ],
        ),
        migrations.CreateModel(
            name='Adderss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('is_default', models.IntegerField()),
                ('user_Adderss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_dev.user')),
            ],
        ),
    ]
